---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ux.sean.example.com
  resources:
  - nodesummaries
  - nodesummarizers
  - workloadsummaries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ux.sean.example.com
  resources:
  - nodesummaries/finalizers
  - nodesummarizers/finalizers
  - workloadsummaries/finalizers
  verbs:
  - update
- apiGroups:
  - ux.sean.example.com
  resources:
  - nodesummaries/status
  - nodesummarizers/status
  - workloadsummaries/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ux.sean.example.com
  resources:
  - workloadsummarizers
  verbs:
  - get
  - list
  - watch
